version: '3.8'

services:
  database:
    image: postgres:15-alpine
    container_name: innovatech_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-innovatech_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-innovatech_pass}
      POSTGRES_DB: ${DB_NAME:-innovatech_platform}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend_net

  back-ventas:
    image: petardorecursos/back-ventas:latest
    container_name: back_ventas_api
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/innovatech_platform
      - SPRING_DATASOURCE_USERNAME=${DB_USER:-innovatech_user}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD:-innovatech_pass}
    ports:
      - "8081:8080"
    depends_on:
      - database
    networks:
      - backend_net

  back-despachos:
    image: petardorecursos/back-despachos:latest
    container_name: back_despachos_api
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/innovatech_platform
      - SPRING_DATASOURCE_USERNAME=${DB_USER:-innovatech_user}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD:-innovatech_pass}
    ports:
      - "8082:8080"
    depends_on:
      - database
    networks:
      - backend_net

  front-despacho:
    image: petardorecursos/front-despacho:latest
    container_name: front_despacho_ui
    restart: always
    ports:
      - "80:8080"
    networks:
      - frontend_net
      - backend_net

networks:
  frontend_net:
    driver: bridge
  backend_net:
    driver: bridge

volumes:
  db_data:
    driver: local